language: shell
os: 
  - linux
#  - osx
#  - windows

before_install:
  - git clone https://github.com/CliMA/ClimateMachine.jl.git
  - git clone https://github.com/atmos-cloud-sim-uj/PySDM.git

install:
  - sudo apt-get install julia
  - sudo pip install -r PySDM/requirements.txt

script:
  - cd ClimateMachine.jl
  - julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'
  - julia --project -e 'using Pkg; Pkg.precompile()'
  - julia --project -e 'using Pkg; Pkg.status()'
  - julia --color=yes --project test/Atmos/Parameterizations/Microphysics/KM_saturation_adjustment.jl

