name: Build Status

defaults:
  run:
    shell: bash
    working-directory: .

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.5.1

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: |
          git clone --depth 1 --branch aj/KM_ncdf_output https://github.com/CliMA/ClimateMachine.jl.git

      - run: |
          cd ClimateMachine.jl
          julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'
          julia --project -e 'using Pkg; Pkg.precompile()'
          julia --project -e 'using Pkg; Pkg.status()'
          julia --color=yes --project test/Atmos/Parameterizations/Microphysics/KM_saturation_adjustment.jl

      - run: |
          git clone --depth 1 https://github.com/atmos-cloud-sim-uj/PySDM.git
          julia -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.pip_interop(true, env); Conda.pip("install -r", "PySDM/requirements.txt")'

      - run: |
          cd PySDM
          julia -e 'using Pkg; Pkg.add("PyCall")'
          julia -e 'using PyCall; pushfirst!(PyVector(pyimport("sys")."path"), ""); example = pyimport("PySDM_examples.ICMW_2012_case_1.example"); example.main()'
